import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"
import { AuthProvider } from "@/providers/AuthContext"

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["200", "400", "700"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.className} antialiased mb-20 md:mb-0`} >
                <AuthProvider>
                    {children}
                </AuthProvider>
            </body>
        </html>
    )
}
